#!/usr/bin/python3
"""handling documentation"""


import unittest
from models.base import Base
"""Handle the various other files that we will use"""


class TestBase(unittest.TestCase):
    """This is where we have our test and this inherits from the Unit test"""
    def test_initialize(self):
        """This test checks whether the function is initialized anytime we create an object or an instance of a class"""
        base = Base()
        self.assertEqual(base.id, 1)


if __name__ == '__main__':
    unittest.main()
